# Benchmark FRESA.CAD BSWIMS final Script




to run the following it is necesary to have installed R on your computer
- R (you can download in https://www.r-project.org/) <br>
- install rpy2 by <code> pip install rpy2 </code>

In [1]:
import numpy as np
import pandas as pd
import sys
from pathlib import Path
import tadpole_algorithms
from tadpole_algorithms.models import BenchmarkSVM_R
from tadpole_algorithms.preprocessing.split import split_test_train_tadpole
#rpy2 libs and funcs
import rpy2.robjects.packages as rpackages
from rpy2.robjects.vectors import StrVector
from rpy2.robjects import r, pandas2ri 
from rpy2 import robjects


In [2]:
# Load D1_D2 train and possible test data set
data_path_train_test = Path("data/TADPOLE_D1_D2.csv")
data_df_train_test = pd.read_csv(data_path_train_test)

# Load D4 evaluation data set 
data_path_eval = Path("data/TADPOLE_D4_corr.csv")
data_df_eval = pd.read_csv(data_path_eval)

# Split data in test, train and evaluation data
train_df, test_df, eval_df = split_test_train_tadpole(data_df_train_test, data_df_eval)

#instanciate the model to get the functions
model = BenchmarkSVM_R()
#set the flag to true to use a preprocessed data
USE_PREPROC = True
#preprocess the data
AdjustedTrainFrame,testingFrame,Train_Imputed,Test_Imputed = model.preproc_tadpole_D1_D2(train_df,USE_PREPROC)
#train and predit 
Forecast_D2 = model.Forecast_D2(AdjustedTrainFrame,testingFrame,Train_Imputed,Test_Imputed,USE_PREPROC)


/opt/anaconda3/lib/python3.7/site-packages/IPython/core/interactiveshell.py:3063: DtypeWarning: Columns (471,473,474,487,488,489,490,491,492,493,494,495,496,497,498,499,500,501,502,503,504,505,506,507,508,509,510,511,512,513,514,515,516,517,518,519,520,521,522,523,524,525,526,527,528,529,530,531,532,533,534,535,536,537,538,539,540,541,542,543,544,545,546,547,548,549,550,551,552,553,554,555,556,557,558,559,560,561,562,563,569,570,572,573,574,575,576,577,578,579,580,581,582,583,584,585,586,587,588,589,590,591,592,593,594,595,596,597,599,601,606,607,608,609,610,611,612,613,614,615,616,617,618,619,620,621,624,625,626,627,628,629,630,631,632,633,634,636,637,638,639,640,641,642,643,644,645,646,647,648,649,650,651,652,653,654,655,656,657,658,659,660,661,663,664,665,666,667,668,669,670,671,672,673,674,675,676,677,678,679,680,681,682,683,684,685,686,687,688,689,690,691,692,693,694,695,696,697,698,699,700,701,702,703,704,705,706,707,708,709,710,711,712,713,714,715,716,717,718,719,720,721,722,723

In [3]:
 AdjustedTrainFrame,testingFrame,Train_Imputed,Test_Imputed = model.preproc_tadpole_D3(train_df,USE_PREPROC)
#train and predit 
Forecast_D3 = model.Forecast_D3(AdjustedTrainFrame,testingFrame,Train_Imputed,Test_Imputed,USE_PREPROC)

In [4]:
from tadpole_algorithms.evaluation import evaluate_forecast
from tadpole_algorithms.evaluation import print_metrics

# Evaluate the model 
dictionary = evaluate_forecast(eval_df, Forecast_D2)

# Print metrics
print_metrics(dictionary)

[[76 10  0]
 [20 69  3]
 [ 2 11 19]]
mAUC (multiclass Area Under Curve): 0.8905512475700299
bca (balanced classification accuracy): 0.894263287696832
adasMAE (ADAS13 Mean Aboslute Error): 9.700607599015592
ventsMAE (Ventricles Mean Aboslute Error): 0.014373537870395907
adasWES (ADAS13 Weighted Error Score): 8.243242488487729
ventsWES (Ventricles Weighted Error Score ): 0.013643624974610162
adasCPA (ADAS13 Coverage Probability Accuracy for 50% Confidence Interval: 0.3949771689497717
ventsCPA (Ventricles Coverage Probability Accuracy for 50% Confidence Interval: 0.44666666666666666
